blank_issues_enabled: false
contact_links:
  - name: 💬 Discussões / Dúvidas Gerais
    url: https://github.com/rodrigocnascimento/lorotv/discussions
    about: Use as Discussões para perguntas que não se encaixam em bug ou melhoria.
